### ISSUE TITLE
大佬，ssr+和passwall的服务端有问题

### ISSUE THREAD

**Issue by gqyun88** [yunxi993/OpenWrt-N1#1]
两者的服务端的加密方式、传输协议、混淆插件等在输入界面全部消失了，之前我在另一个openwrt下用同样版本的ssr+显示是全的，不知哪里出了问题，请大佬检查一下，谢谢

**Comment by gqyun88** [comment]
我的意思是如果服务端用shadowSOCKs的话，如果用SOCKs的话，显示是没问题的

**Comment by yunxi993** [comment]
因为是精简，所以依赖没有编译进去.

**Comment by gqyun88** [comment]
希望下一版能编译进去，拜托！

**Comment by gqyun88** [comment]
另外网络——DHCP/DNS——静态地址分配的选项里可不可以增加tag项，以便分别管理DHCP组，不情之请，见笑了

**Comment by yunxi993** [comment]
> 另外网络——DHCP/DNS——静态地址分配的选项里可不可以增加tag项，以便分别管理DHCP组，不情之请，见笑了

好的，tag是个什么东西.

**Comment by gqyun88** [comment]
> > 另外网络——DHCP/DNS——静态地址分配的选项里可不可以增加tag项，以便分别管理DHCP组，不情之请，见笑了
> 
> 好的，tag是个什么东西.

就是分类管理DHCP组的标识符，我用它来管理例如，某些mac码的设备采用某个网关或DNS，另外一组的采用另一个网关和DNS，我也不是很懂，大概是这个意思

**Comment by yunxi993** [comment]
> 就是分类管理DHCP组的标识符，我用它来管理例如，某些mac码的设备采用某个网关或DNS，另外一组的采用另一个网关和DNS，我也不是很懂，大概是这个意思

你说的是多宽带分流吗？

**Comment by gqyun88** [comment]
> > 就是分类管理DHCP组的标识符，我用它来管理例如，某些mac码的设备采用某个网关或DNS，另外一组的采用另一个网关和DNS，我也不是很懂，大概是这个意思
> 
> 你说的是多宽带分流吗？

不是多宽带分流，是局域网内部分流，有的走主路由不翻墙，有的走旁路由翻墙

**Comment by yunxi993** [comment]
> 不是多宽带分流，是局域网内部分流，有的走主路由不翻墙，有的走旁路由翻墙

这个功能ssr && passwall都可以实现啊

**Comment by gqyun88** [comment]
> > 不是多宽带分流，是局域网内部分流，有的走主路由不翻墙，有的走旁路由翻墙
> 
> 这个功能ssr && passwall都可以实现啊

哦，这个我得研究一下。另外，大佬，你新发布的两个版本我应该下哪个？大杂烩吧

**Comment by yunxi993** [comment]
> 哦，这个我得研究一下。另外，大佬，你新发布的两个版本我应该下哪个？大杂烩吧

对的
