### ISSUE TITLE
openwrt_s905d_n1_R21.7.26_k5.4.137-flippy-62+o 无线无法启用

### ISSUE THREAD

**Issue by laoyur** [yunxi993/OpenWrt-N1#2]
大佬，N1刷完后无线一直是“未启用或未关联”，咋整啊

**Comment by yunxi993** [comment]
> 大佬，N1刷完后无线一直是“未启用或未关联”，咋整啊

因为在打包的时候关闭无线了，不建议的使用盒子的WIFI（包括 flippy)会出现很多莫名其妙的问题，影响你日常使用、爬墙速度、和重启、断网之类的.

**Comment by laoyur** [comment]
感谢答复。
WiFi不稳？这么严重？
晕了，我特意买了个N1，准备配合4G模块、小米插座做果园的远程水泵 😂
不行，我还是得试试，我找到其他人的固件可以用wifi的，但是装不上 `kmod-usb-net-rndis`

```
root@OpenWrt:~# opkg --force-depends install kmod-usb-net-rndis
Unknown package 'kmod-usb-net-rndis'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-mii
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-mii found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-nls-base
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net-cdc-ether
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net-cdc-ether found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net-rndis
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net-rndis found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-usb-net-rndis.
```

请问是否必须得我自己编译固件了？对openwrt不熟，求大佬指条路

**Comment by yunxi993** [comment]
> 感谢答复。
> WiFi不稳？这么严重？
> 晕了，我特意买了个N1，准备配合4G模块、小米插座做果园的远程水泵 😂
> 不行，我还是得试试，我找到其他人的固件可以用wifi的，但是装不上 `kmod-usb-net-rndis`
> 
> ```
> root@OpenWrt:~# opkg --force-depends install kmod-usb-net-rndis
> Unknown package 'kmod-usb-net-rndis'.
> Collected errors:
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-mii
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-mii found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-nls-base
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-core
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net-cdc-ether
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net-cdc-ether found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.137-1-3636d6195a5817ddab0e8f28f2485e7b) for kmod-usb-net-rndis
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-net-rndis found, but incompatible with the architectures configured
>  * opkg_install_cmd: Cannot install package kmod-usb-net-rndis.
> ```
> 
> 请问是否必须得我自己编译固件了？对openwrt不熟，求大佬指条路

F大的估计那可以啊，一般F大的固件是最全的，其它大部人编译的固件都是根据自己的使用习惯精简的.
要用WIFI还是需要硬路由当AP来用.

**Comment by laoyur** [comment]
找到一篇不错的文章 https://hamy.io/post/0015/how-to-compile-openwrt-and-still-use-the-official-repository/
简单来说：自己编译的固件，是不可能通过官方源安装`kmod`的
老老实实自己编译吧
